---
- name: Configure Frontend (Ubuntu)
  hosts: server_role_frontend_server
  become: true
  roles:
    - frontend_server

- name: Configure Redis (Rocky)
  hosts: server_role_redis_server
  become: true
  roles:
    - redis_server
